// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajhqeittudltmheuitvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqaHFlaXR0dWRsdG1oZXVpdHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTg2MDIsImV4cCI6MjA2Njg3NDYwMn0.UYpmYvv0wtmoJL99JQJE4pWqA-N2NQIuyAKiTkf06vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});