name: CICD

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: ${{ github.repository }}
  DOCKER_CONTAINER: hr

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: [self-hosted, intranet]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Docker build
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha

  deploy:
    needs: build
    runs-on: [self-hosted, intranet]

    steps:
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Deploy frontend service using Docker Swarm
        env:
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        run: |
          echo $SUDO_PASSWORD | sudo -S docker stack deploy -c /home/withuscpa/hr/docker-compose.yml --with-registry-auth watt
